"""
This file contains the column names for the dataframes used in the
nhsbt_import module.
"""

# TODO: [NHSBT-9] Could consider putting these in a table somewhere
df_columns = {
    "new_patients": [
        "UKTSSA_No",
        "Match Type",
        "Surname - NHSBT",
        "Forename - NHSBT",
        "Sex - NHSBT",
        "Date Birth - NHSBT",
        "Date Death - NHSBT",
        "NHS Number - NHSBT",
    ],
    "updated_patients": [
        "UKTSSA_No",
        "RR_No",
        "Match Type",
        "Surname - NHSBT",
        "Surname - RR",
        "Forename - NHSBT",
        "Forename - RR",
        "Sex - NHSBT",
        "Sex - RR",
        "Date Birth - NHSBT",
        "Date Birth - RR",
        "Date Death - NHSBT",
        "Date Death - RR",
        "NHS Number - NHSBT",
        "NHS Number - RR",
        "CHI Number - NHSBT",
        "CHI Number - RR",
        "HSC Number - NHSBT",
        "HSC Number - RR",
        "Postcode - NHSBT",
        "Postcode - RR",
    ],
    "new_transplants": [
        "Match Type",
        "UKTSSA_No",
        "RR_No",
        "Transplant ID - NHSBT",
        "Registration ID - NHSBT",
        "Transplant Date - NHSBT",
        "Transplant Type - NHSBT",
        "Transplant Organ - NHSBT",
        "Transplant Unit - NHSBT",
        "Registration Date - NHSBT",
        "Registration Date Type - NHSBT",
        "Registration End Date - NHSBT",
        "Registration End Status - NHSBT",
        "Transplant Consideration - NHSBT",
        "Transplant Dialysis - NHSBT",
        "Transplant Relationship - NHSBT",
        "Transplant Sex - NHSBT",
        "Cause of Failure - NHSBT",
        "Cause of Failure Text - NHSBT",
        "CIT Mins - NHSBT",
        "HLA Mismatch - NHSBT",
        "UKT Suspension - NHSBT",
    ],
    "updated_transplants": [
        "UKTSSA_No",
        "Registration ID - RR",
        "Match Type",
        "Transplant ID - NHSBT",
        "Transplant ID - RR",
        "Transplant Date - NHSBT",
        "Transplant Date - RR",
        "Transplant Type - NHSBT",
        "Transplant Type - RR",
        "Transplant Organ - NHSBT",
        "Transplant Organ - RR",
        "Transplant Unit - NHSBT",
        "Transplant Unit - RR",
        "Registration Date - NHSBT",
        "Registration Date - RR",
        "Registration Date Type - NHSBT",
        "Registration Date Type - RR",
        "Registration End Date - NHSBT",
        "Registration End Date - RR",
        "Registration End Status - NHSBT",
        "Registration End Status - RR",
        "Transplant Consideration - NHSBT",
        "Transplant Consideration - RR",
        "Transplant Dialysis - NHSBT",
        "Transplant Dialysis - RR",
        "Transplant Relationship - NHSBT",
        "Transplant Relationship - RR",
        "Transplant Sex - NHSBT",
        "Transplant Sex - RR",
        "Cause of Failure - NHSBT",
        "Cause of Failure - RR",
        "Cause of Failure Text - NHSBT",
        "Cause of Failure Text - RR",
        "CIT Mins - NHSBT",
        "CIT Mins - RR",
        "HLA Mismatch - NHSBT",
        "HLA Mismatch - RR",
        "UKT Suspension - NHSBT",
        "UKT Suspension - RR",
    ],
    "missing_patients": [
        "UKTSSA_No",
        "Match Type",
        "Surname - RR",
        "Forename - RR",
        "Sex - RR",
        "Date Birth - RR",
        "NHS Number - RR",
        "CHI Number - RR",
        "HSC Number - RR",
    ],
    "missing_transplants": [
        "Match Type",
        "UKTSSA_No",
        "RR_No",
        "Transplant ID - RR",
        "Registration ID - RR",
        "Transplant Date - RR",
        "Transplant Type - RR",
        "Transplant Organ - RR",
        "Transplant Unit - RR",
        "Registration Date - RR",
        "Registration Date Type - RR",
        "Registration End Date - RR",
        "Registration End Status - RR",
        "Transplant Consideration - RR",
        "Transplant Dialysis - RR",
        "Transplant Relationship - RR",
        "Transplant Sex - RR",
        "Cause of Failure - RR",
        "Cause of Failure Text - RR",
        "CIT Mins - RR",
        "HLA Mismatch - RR",
        "UKT Suspension - RR",
    ],
    "deleted_patients": [
        "UKTSSA_No",
        "RR_No",
        "Match Type",
        "Surname - NHSBT",
        "Surname - RR",
        "Forename - NHSBT",
        "Forename - RR",
        "Sex - NHSBT",
        "Sex - RR",
        "Date Birth - NHSBT",
        "Date Birth - RR",
        "NHS Number - NHSBT",
        "NHS Number - RR",
        "CHI Number - NHSBT",
        "CHI Number - RR",
        "HSC Number - NHSBT",
        "HSC Number - RR",
    ],
}
