# TODO: Could consider putting these in a table somewhere
df_columns = {
    "new_patients_df": [
        "UKTSSA_No",
        "Match Type",
        "File Surname",
        "File Forename",
        "File Sex",
        "File Date Birth",
        "File NHS Number",
    ],
    "updated_patients_df": [
        "UKTSSA_No",
        "Match Type",
        "File Surname",
        "File Forename",
        "File Sex",
        "File Date Birth",
        "File NHS Number",
        "DB RR_No",
        "DB Surname",
        "DB Forename",
        "DB Sex",
        "DB Date Birth",
        "DB NHS Number",
    ],
    "new_transplant_df": [
        "Match Type",
        "UKTSSA_No",
        "RR_No",
        "Transplant ID",
        "Registration ID",
        "Transplant Date",
        "Transplant Type",
        "Transplant Organ",
        "Transplant Unit",
        "Registration Date",
        "Registration Date Type",
        "Registration End Date",
        "Registration End Status",
        "Transplant Consideration",
        "Transplant Dialysis",
        "Transplant Relationship",
        "Transplant Sex",
        "Cause of Failure",
        "Cause of Failure Text",
        "CIT Mins",
        "HLA Mismatch",
        "UKT Suspension",
    ],
    "updated_transplant_df": [
        "Match Type",
        "UKTSSA_No",
        "RR_No",
        "Transplant ID - File",
        "Transplant ID - DB",
        "Registration ID - File",
        "Registration ID - DB",
        "Transplant Date - File",
        "Transplant Date - DB",
        "Transplant Type - File",
        "Transplant Type - DB",
        "Transplant Organ - File",
        "Transplant Organ - DB",
        "Transplant Unit - File",
        "Transplant Unit - DB",
        "Registration Date - File",
        "Registration Date - DB",
        "Registration Date Type - File",
        "Registration Date Type - DB",
        "Registration End Date - File",
        "Registration End Date - DB",
        "Registration End Status - File",
        "Registration End Status - DB",
        "Transplant Consideration - File",
        "Transplant Consideration - DB",
        "Transplant Dialysis - File",
        "Transplant Dialysis - DB",
        "Transplant Relationship - File",
        "Transplant Relationship - DB",
        "Transplant Sex - File",
        "Transplant Sex - DB",
        "Cause of Failure - File",
        "Cause of Failure - DB",
        "Cause of Failure Text - File",
        "Cause of Failure Text - DB",
        "CIT Mins - File",
        "CIT Mins - DB",
        "HLA Mismatch - File",
        "HLA Mismatch - DB",
        "UKT Suspension - File",
        "UKT Suspension - DB",
    ],
}
