name: Pull Request

on:
  push:
    branches-ignore:
      - main

  workflow_dispatch:

jobs:
  open-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate Token
        uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.TOKEN_APP_ID }}
          private_key: ${{ secrets.TOKEN_APP_KEY }}

      - name: Git Setup
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Committer Email
        id: committer_email
        run: |
          COMMITTER_EMAIL=$(git log -n 1 --pretty=format:%ae)
          echo "committer_email=${COMMITTER_EMAIL}" >> $GITHUB_OUTPUT

      - name: Extract Branch Name
        id: extract_branch_name
        run: |
          BRANCH_NAME=$(basename ${{ github.event.ref }})
          echo "branch_name=${BRANCH_NAME}" >> $GITHUB_OUTPUT

      # - name: Extract First Commit Message
      #   id: extract_message
      #   run: |
      #     FIRST_COMMIT_MESSAGE=$(git log remotes/origin/main..${{ steps.extract_branch_name.outputs.branch_name }} --oneline --pretty=format:"%s" | tail -1)
      #     echo "commit_message=${FIRST_COMMIT_MESSAGE}" >> $GITHUB_OUTPUT
      #     PR_BODY=$(git log remotes/origin/main..${{ steps.extract_branch_name.outputs.branch_name }} --oneline --pretty=format:"%B" | tail -1)
      #     echo "pr_body=${PR_BODY}" >> $GITHUB_OUTPUT

      - name: Extract Commit Messages
        id: extract_messages
        run: |
          COMMIT_MESSAGES=$(git log remotes/origin/main..${{ steps.extract_branch_name.outputs.branch_name }} --oneline --pretty=format:"%s" | grep -E '^(feat!|feat|fix|docs)')
          echo "commit_messages=${COMMIT_MESSAGES}" >> $GITHUB_OUTPUT
          PR_BODY=$(git log remotes/origin/main..${{ steps.extract_branch_name.outputs.branch_name }} --oneline --pretty=format:"%B" | grep -E '^(feat!|feat|fix|docs)')
          echo "pr_body=${PR_BODY}" >> $GITHUB_OUTPUT

      - name: Determine Superior Commit
        id: superior_commit
        run: |
          SUPERIOR_COMMIT=$(echo "${{ steps.extract_messages.outputs.commit_messages }}" | sort -r | head -n 1)
          echo "superior_commit=${SUPERIOR_COMMIT}" >> $GITHUB_OUTPUT

          COUNT_SUPERIOR=$(echo "${{ steps.extract_messages.outputs.commit_messages }}" | grep -c "${SUPERIOR_COMMIT}")
          echo "count_superior=${COUNT_SUPERIOR}" >> $GITHUB_OUTPUT

          if [ "$COUNT_SUPERIOR" -gt 1 ]; then
            echo "Exiting workflow. Two or more instances of a superior commit found."
            exit 0
          fi

      - name: Get Current Date
        id: get_current_date
        run: |
          CURRENT_DATE=$(date +"%Y-%m-%d")
          echo "current_date=${CURRENT_DATE}" >> $GITHUB_OUTPUT

      - name: Render Template
        id: template
        uses: chuhlomin/render-template@v1
        with:
          template: .github/pull_request_template.md
          vars: |
            pr_date: ${{ steps.get_current_date.outputs.current_date }}
            pr_feature: "${{ steps.extract_messages.outputs.commit_messages }}"
            pr_notes: ${{ steps.extract_messages.outputs.pr_body }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ steps.generate-token.outputs.token }}
          branch: ${{ github.event.ref }}
          commit-message: ${{ steps.superior_commit.outputs.greatest_commit }}
          title: ${{ steps.superior_commit.outputs.greatest_commit }}
          body: ${{ steps.template.outputs.result }}
          base: main
