name: Pull Request

on:
  push:
    branches-ignore:
      - main

  workflow_dispatch:

jobs:
  open-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate Token
        uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.TOKEN_APP_ID }}
          private_key: ${{ secrets.TOKEN_APP_KEY }}

      - name: Git Setup
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Committer Email
        id: committer_email
        run: |
          COMMITTER_EMAIL=$(git log -n 1 --pretty=format:%ae)
          echo "committer_email=${COMMITTER_EMAIL}" >> $GITHUB_OUTPUT

      - name: Extract Branch Name
        id: extract_branch_name
        run: |
          BRANCH_NAME=$(basename ${{ github.event.ref }})
          echo "branch_name=${BRANCH_NAME}" >> $GITHUB_OUTPUT

      - name: Extract First Commit Message
        id: extract_message
        run: |
          FIRST_COMMIT_MESSAGE=$(git log remotes/origin/main..${{ steps.extract_branch_name.outputs.branch_name }} --oneline --pretty=format:"%s" | tail -1)
          echo "commit_message=${FIRST_COMMIT_MESSAGE}" >> $GITHUB_OUTPUT
          PR_BODY=$(git log remotes/origin/main..${{ steps.extract_branch_name.outputs.branch_name }} --oneline --pretty=format:"%B" | tail -1)
          echo "pr_body=${PR_BODY}" >> $GITHUB_OUTPUT

      - name: Get Current Date
        id: get_current_date
        run: |
          CURRENT_DATE=$(date +"%Y-%m-%d")
          echo "current_date=${CURRENT_DATE}" >> $GITHUB_OUTPUT

      - name: Render Template
        id: template
        uses: chuhlomin/render-template@v1
        with:
          template: .github/pull-request-template.md
          vars: |
            pr_date: ${{ steps.get_current_date.outputs.current_date }}
            pr_feature: "${{ steps.extract_message.outputs.commit_message }}"
            pr_notes: ${{ steps.extract_message.outputs.pr_body }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ steps.generate-token.outputs.token }}
          branch: ${{ github.event.ref }}
          commit-message: ${{ steps.extract_message.outputs.commit_message }}
          title: ${{ steps.extract_message.outputs.commit_message }}
          body: ${{ steps.template.outputs.result }}
          base: main
