name: Pull Request

on:
  push:
    branches-ignore:
      - main

  workflow_dispatch:

jobs:
  open-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate Token
        uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.TOKEN_APP_ID }}
          private_key: ${{ secrets.TOKEN_APP_KEY }}

      - name: Set Up Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Extract Branch Name
        id: extract_branch_name
        run: |
          BRANCH_NAME=$(basename ${{ github.event.ref }})
          echo "branch_name=${BRANCH_NAME}" >> $GITHUB_OUTPUT

      - name: Extract First Commit Message
        id: extract_message
        run: |
          FIRST_COMMIT_MESSAGE=$(git log remotes/origin/main..${{ steps.extract_branch_name.outputs.branch_name }} --oneline --pretty=format:"%s" | tail -1)
          echo "commit_message=${FIRST_COMMIT_MESSAGE}" >> $GITHUB_OUTPUT
          PR_BODY=$(git log remotes/origin/main..${{ steps.extract_branch_name.outputs.branch_name }} --oneline --pretty=format:"%B" | tail -1)
          echo "pr_body=${PR_BODY}" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ steps.generate-token.outputs.token }}
          branch: ${{ github.event.ref }}
          commit-message: ${{ steps.extract_message.outputs.commit_message }}
          title: ${{ steps.extract_message.outputs.commit_message }}
          body: ${{ steps.extract_message.outputs.pr_body }}
          base: main
          committer: "${{ github.actor }}@${{ vars.EMAIL_DOMAIN }}"
