name: Python Release

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Poetry
        uses: Gr1N/setup-poetry@v8

      # - id: extract_package_name
      #   name: Extract Package Name
      #   run: |
      #     package_name=$(poetry version | cut -d ' ' -f 1)
      #     echo $package_name

      - name: Release Please
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: python
          package-name: nhsbt-import
