name: Python Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform:
          - ubuntu-latest
          - windows-latest
        python-version: ["3.11"]

    env:
      DIRECTORY_TO_SCAN: ./nhsbt_import
      TODO_REGEX: 'TODO:(?!\s*\[[A-Za-z0-9-]+\])'

    steps:
      - uses: actions/checkout@v4
      - uses: Gr1N/setup-poetry@v8

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: poetry install

      - name: Test with tox
        run: poetry run tox

      - name: TODO check
        run: |
          if [ "${{ runner.os }}" == "Windows" ]; then
            $result = Get-ChildItem -Path $env:DIRECTORY_TO_SCAN -Filter *.py -Recurse | ForEach-Object { Get-Content $_.FullName | Select-String -Pattern $env:TODO_REGEX }
            if ($result) {
                echo "Non-matching TODO comments found:"
                echo $result
                exit 1
            }
          else
            result=$(find "$DIRECTORY_TO_SCAN" -type f -name "*.py" -exec grep -Hn -P "$TODO_REGEX" {} \;)
            if [ -n "$result" ]; then
            echo "Non-matching TODO comments found:"
            echo "$result"
            exit 1
            fi
          fi
