name: release-please

on:
  push:
    branches:
      - action-playground-main

permissions:
  contents: write
  pull-requests: write



jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:

      - name : Checkout
        uses: actions/checkout@v2

      - name: Extract Package Name
        run: |
          package_name=$(jq -r '.tool.poetry.name' pyproject.toml)
          echo "::set-output name=package_name::$package_name"
      


      - name: Release Please
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: ${{ steps.extract_package_name.outputs.package_name }}